### ISSUE TITLE
Find_pattern set up for YAML 

### ISSUE THREAD

**Issue by roxyisat-rex** [sandberg-lab/Smart-seq3#6]
Hi
Was using zUMIs as a part of the protocol for analysing SS3 data. 
However I realised the directions for setting up the .yaml file is quite different from them and you guys.
On their wiki on setting up the yaml, there is no mention of needing a find_pattern for a 11bp tag sequence, while on your main readme page, it's said the yaml should be set up like the below with find_pattern filled in with a 11bp tag sequence. 
I am a little confused as to which to follow? Are there any resources that explains this in a bit more detail? Also is it the literal` ATTGCGCAATG` sequence? Or am I supposed to obtain this information somewhere, my data is with Miseq, and I can't find anything about a 11bp tag index in the metadata files. Some help would be much appreciated, thank you! 

```
file1:
    name: /mnt/storage2/temp_workdir/Undetermined_S0_L003_R1_001.fastq.gz
    base_definition:
      - cDNA(23-150)
      - UMI(12-19)
    find_pattern: ATTGCGCAATG
```
